"""add hashed_password

Revision ID: bc51eb36613c
Revises: c2ba5ff0f84a
Create Date: 2026-05-26 19:09:09.096506
"""
from alembic import op
import sqlalchemy as sa


revision = 'bc51eb36613c'
down_revision = 'c2ba5ff0f84a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
